name: CI CD PIPELINE FOR JAVA WEB APPLICATION
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  Sample_CICD_Pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setp 1 :Install java
        run: | 
          sudo apt-get update -y 
          sudo apt install openjdk-11-jdk-headless -y
      - name: Setp 2 :Checking Java Version
        run: |
          sudo java -version
      - name: Setp 3 :Install Maven
        run: |
          sudo apt-get install maven -y
      - name: Setp4 :Checking Maven Version
        run: |
          mvn --version
      - name: Setp5 :create archive file
        run: |
          mvn package
          mkdir dev && cp target/*.war dev
      - name: Step 5 :Generate SSH key Gen and Copy ID
        run: |
          ssh-keygen -f ~/.ssh/id_rsa -N ""
          ssh-copy-id -i $HOME/.ssh/id_rsa.pub keerthi_devops26@34.66.133.171
      - name: Step6 :Install sshpass
        run: |
          sudo apt-get install sshpass -y
      - name: Step7 :Deploy war to GCP Tomcat Server
        run: |
          sshpass -p 'keerthi_devops26@34.66.133.171' scp -o StrictHostKeyChecking=no -r dev/*.war keerthi_devops26@34.66.133.171:/opt/tomcat/webapps/
